# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class AccountLinkAction(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """AccountLinkAction."""

    CREATE_AND_LINK_NEW_ACCOUNT = "CreateAndLinkNewAccount"
    LINK_TO_EXISTING_ACCOUNT = "LinkToExistingAccount"
    LEAVE_UNLINKED = "LeaveUnlinked"


class OperationTypes(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """OperationTypes."""

    CREATED = "Created"
    UPDATED = "Updated"
    DELETED = "Deleted"
    NONE = "None"


class PlayerIdentityProvider(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """PlayerIdentityProvider."""

    ANDROID_DEVICE = "AndroidDevice"
    APPLE = "Apple"
    CUSTOM_ID = "CustomId"
    EMAIL = "Email"
    FACEBOOK_INSTANT_GAMES = "FacebookInstantGames"
    GAME_CENTER = "GameCenter"
    GOOGLE = "Google"
    I_O_S_DEVICE = "iOSDevice"
    KONGREGATE = "Kongregate"
    NINTENDO_SWITCH_DEVICE = "NintendoSwitchDevice"
    NINTENDO_ACCOUNT = "NintendoAccount"
    OPEN_ID = "OpenId"
    PSN = "PSN"
    SERVER_CUSTOM_ID = "ServerCustomId"
    STEAM = "Steam"
    TWITCH = "Twitch"
    USERNAME = "Username"
    XBOX = "Xbox"
    GOOGLE_PLAY_GAMES = "GooglePlayGames"
