# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._models import CustomErrorResponseWithXMsErrorCodeHeader
from ._models import Discovery
from ._models import DiscoveryCreationParameters
from ._models import DiscoveryLroResponse
from ._models import DiscoverySpecialFile
from ._models import DiscoveryUpload
from ._models import LongRunningOperationWithResponseHeaders
from ._models import Upload
from ._models import UploadCreationParameters
from ._models import UploadDataFile
from ._models import UploadLroResponse
from ._models import UploadResultMeasurement
from ._models import UploadSpecialFile

from ._enums import DiscoveryOperationType
from ._enums import DiscoveryStatus
from ._enums import LongRunningOperationStatus
from ._enums import UploadOperationType
from ._enums import UploadStatus
from ._patch import __all__ as _patch_all
from ._patch import *  # type: ignore # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "CustomErrorResponseWithXMsErrorCodeHeader",
    "Discovery",
    "DiscoveryCreationParameters",
    "DiscoveryLroResponse",
    "DiscoverySpecialFile",
    "DiscoveryUpload",
    "LongRunningOperationWithResponseHeaders",
    "Upload",
    "UploadCreationParameters",
    "UploadDataFile",
    "UploadLroResponse",
    "UploadResultMeasurement",
    "UploadSpecialFile",
    "DiscoveryOperationType",
    "DiscoveryStatus",
    "LongRunningOperationStatus",
    "UploadOperationType",
    "UploadStatus",
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()
