# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class DiscoveryOperationType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The supported actions on discovery."""

    #: The process of completing the discovery
    COMPLETE_DISCOVERY = "CompleteDiscovery"
    #: The process of finalizing the file list of the discovery
    FINALIZE_FILE_LIST = "FinalizeFileList"
    #: The process of cancelling the discovery
    ABORT_DISCOVERY = "AbortDiscovery"


class DiscoveryStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The status of the discovery."""

    #: The discovery process has been initiated
    CREATED = "Created"
    #: The system is analyzing the discovery manifest file uploaded by the client and generating the
    #: upload information for uploading special files.
    GENERATING_SPECIAL_FILES_UPLOAD_INFO = "GeneratingSpecialFilesUploadInfo"
    #: The system has analyzed the discovery manifest file and generated the upload information for
    #: uploading special files.
    GENERATED_SPECIAL_FILES_UPLOAD_INFO = "GeneratedSpecialFilesUploadInfo"
    #: The system is processing the special files uploaded by the client
    COMPLETING = "Completing"
    #: The system has finished the analysis of special files
    COMPLETED = "Completed"
    #: The system is cancelling the discovery process
    ABORTING = "Aborting"
    #: The discovery process has been aborted
    ABORTED = "Aborted"
    #: The discovery process has been failed
    FAILED = "Failed"


class LongRunningOperationStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """LongRunningOperationStatus."""

    CREATED = "Created"
    IN_PROGRESS = "InProgress"
    SUCCEEDED = "Succeeded"
    FAILED = "Failed"
    CANCELED = "Canceled"


class UploadOperationType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The supported operations of the upload."""

    #: The process of finalizing the file list of the upload
    FINALIZE_FILE_LIST = "FinalizeFileList"
    #: The process of sharding the files for the upload
    SHARD_FILES = "ShardFiles"
    #: The process of completing the upload
    COMPLETE_UPLOAD = "CompleteUpload"
    #: The process of cancelling the upload
    ABORT_UPLOAD = "AbortUpload"


class UploadStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """The state of the upload."""

    #: The upload process has been initiated. The client should upload the upload manifest file using
    #: the SAS-signed upload URI provided by the system
    CREATED = "Created"
    #: The system is analyzing the upload manifest file uploaded by the client and generating the
    #: upload information for uploading special files.
    GENERATING_SPECIAL_FILES_UPLOAD_INFO = "GeneratingSpecialFilesUploadInfo"
    #: The system has analyzed the upload manifest file and generated the upload information for
    #: uploading special files.
    GENERATED_SPECIAL_FILES_UPLOAD_INFO = "GeneratedSpecialFilesUploadInfo"
    #: The system is sharding the files and generating the upload information for uploading data
    #: files.
    GENERATING_DATA_FILES_UPLOAD_INFO = "GeneratingDataFilesUploadInfo"
    #: The system has sharded the files and generated the upload information for uploading data files.
    #: The client should upload the measurement files using the SAS-signed upload URIs provided by the
    #: system.
    GENERATED_DATA_FILES_UPLOAD_INFO = "GeneratedDataFilesUploadInfo"
    #: The system is completing the upload process (creating measurements etc.)
    COMPLETING = "Completing"
    #: The system completed the upload process
    COMPLETED = "Completed"
    #: The system is cancelling the upload process
    ABORTING = "Aborting"
    #: The system cancelled the upload process
    ABORTED = "Aborted"
    #: The system marked the upload process as failed
    FAILED = "Failed"
