# coding=utf-8
# pylint: disable=too-many-lines
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

import sys
from typing import Any, List, Mapping, Optional, TYPE_CHECKING, Union, overload

from .. import _model_base
from .._model_base import rest_field

if sys.version_info >= (3, 9):
    from collections.abc import MutableMapping
else:
    from typing import MutableMapping  # type: ignore  # pylint: disable=ungrouped-imports

if TYPE_CHECKING:
    # pylint: disable=unused-import,ungrouped-imports
    from .. import models as _models
JSON = MutableMapping[str, Any]  # pylint: disable=unsubscriptable-object


class CustomErrorResponseWithXMsErrorCodeHeader(_model_base.Model):
    """Default error response with custom header.

    All required parameters must be populated in order to send to Azure.

    :ivar error: The error object. Required.
    :vartype error: ~adp.models.Error
    :ivar x_ms_error_code: Error code for specific error that occurred. Required.
    :vartype x_ms_error_code: str
    """

    error: "_models.Error" = rest_field()
    """The error object. Required. """
    x_ms_error_code: str = rest_field(name="x-ms-error-code")
    """Error code for specific error that occurred. Required. """

    @overload
    def __init__(
        self,
        *,
        error: "_models.Error",
        x_ms_error_code: str,
    ):
        ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]):
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """
        ...

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class Discovery(_model_base.Model):
    """A discovery resource.

    Variables are only populated by the server, and will be ignored when sending a request.

    All required parameters must be populated in order to send to Azure.

    :ivar discovery_id: The discovery identifier. Required.
    :vartype discovery_id: str
    :ivar external_package_id: ID of the external package (for example, the disk which contained
     data) which was used upon the creation of upload.
    :vartype external_package_id: str
    :ivar manifest_upload_uri: SAS signed URI for uploading or reading the discovery manifest file
     on Azure Storage.
     Note, if the discovery status is 'Created' then the URI is signed with 'Write' permissions,
     otherwise with 'Read' permission.
     This URI expires in 24 hours.
    :vartype manifest_upload_uri: str
    :ivar status: The discovery status. Known values are: "Created",
     "GeneratingSpecialFilesUploadInfo", "GeneratedSpecialFilesUploadInfo", "Completing",
     "Completed", "Aborting", "Aborted", and "Failed".
    :vartype status: str or ~adp.models.DiscoveryStatus
    """

    discovery_id: str = rest_field(name="discoveryId")
    """The discovery identifier. Required. """
    external_package_id: Optional[str] = rest_field(name="externalPackageId", readonly=True)
    """ID of the external package (for example, the disk which contained data) which was used upon the creation of upload. """
    manifest_upload_uri: Optional[str] = rest_field(name="manifestUploadUri", readonly=True)
    """SAS signed URI for uploading or reading the discovery manifest file on Azure Storage.
Note, if the discovery status is 'Created' then the URI is signed with 'Write' permissions, otherwise with 'Read' permission.
This URI expires in 24 hours. """
    status: Optional[Union[str, "_models.DiscoveryStatus"]] = rest_field(readonly=True)
    """The discovery status. Known values are: \"Created\", \"GeneratingSpecialFilesUploadInfo\", \"GeneratedSpecialFilesUploadInfo\", \"Completing\", \"Completed\", \"Aborting\", \"Aborted\", and \"Failed\"."""

    @overload
    def __init__(
        self,
        *,
        discovery_id: str,
    ):
        ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]):
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """
        ...

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class DiscoveryCreationParameters(_model_base.Model):
    """Discovery resource creation parameters.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar external_package_id: ID of the external package (for example, the disk which contained
     data) which was used upon the creation of upload.
    :vartype external_package_id: str
    """

    external_package_id: Optional[str] = rest_field(name="externalPackageId", readonly=True)
    """ID of the external package (for example, the disk which contained data) which was used upon the creation of upload. """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class DiscoveryLroResponse(_model_base.Model):
    """Discovery long running operation response.

    All required parameters must be populated in order to send to Azure.

    :ivar operation_id: The operation Id. Required.
    :vartype operation_id: str
    :ivar status: The operation status. Required. Known values are: "Created", "InProgress",
     "Succeeded", "Failed", and "Canceled".
    :vartype status: str or ~adp.models.LongRunningOperationStatus
    :ivar operation_type: The operation type. Known values are: "CompleteDiscovery",
     "FinalizeFileList", and "AbortDiscovery".
    :vartype operation_type: str or ~adp.models.DiscoveryOperationType
    :ivar error: The operation error.
    :vartype error: ~adp.models.Error
    """

    operation_id: str = rest_field(name="operationId")
    """The operation Id. Required. """
    status: Union[str, "_models.LongRunningOperationStatus"] = rest_field()
    """The operation status. Required. Known values are: \"Created\", \"InProgress\", \"Succeeded\", \"Failed\", and \"Canceled\"."""
    operation_type: Optional[Union[str, "_models.DiscoveryOperationType"]] = rest_field(name="operationType")
    """The operation type. Known values are: \"CompleteDiscovery\", \"FinalizeFileList\", and \"AbortDiscovery\"."""
    error: Optional["_models.Error"] = rest_field()
    """The operation error. """

    @overload
    def __init__(
        self,
        *,
        operation_id: str,
        status: Union[str, "_models.LongRunningOperationStatus"],
        operation_type: Optional[Union[str, "_models.DiscoveryOperationType"]] = None,
        error: Optional["_models.Error"] = None,
    ):
        ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]):
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """
        ...

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class DiscoverySpecialFile(_model_base.Model):
    """A discovery special file resource.

    All required parameters must be populated in order to send to Azure.

    :ivar client_file_name: Client file name. Required.
    :vartype client_file_name: str
    :ivar file_upload_uri: File name on storage. Required.
    :vartype file_upload_uri: str
    """

    client_file_name: str = rest_field(name="clientFileName")
    """Client file name. Required. """
    file_upload_uri: str = rest_field(name="fileUploadUri")
    """File name on storage. Required. """

    @overload
    def __init__(
        self,
        *,
        client_file_name: str,
        file_upload_uri: str,
    ):
        ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]):
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """
        ...

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class DiscoveryUpload(_model_base.Model):
    """A discovery upload resource.

    Variables are only populated by the server, and will be ignored when sending a request.

    All required parameters must be populated in order to send to Azure.

    :ivar upload_id: Upload identifier. Required.
    :vartype upload_id: str
    :ivar manifest_download_uri: SAS signed URI for downloading the manifest file from Azure
     Storage.
     The manifest file contains list of all files in the group.
     This URI expires in 24 hours. Required.
    :vartype manifest_download_uri: str
    :ivar resource_endpoint: The endpoint uri of the owning resource.
    :vartype resource_endpoint: str
    """

    upload_id: str = rest_field(name="uploadId")
    """Upload identifier. Required. """
    manifest_download_uri: str = rest_field(name="manifestDownloadUri")
    """SAS signed URI for downloading the manifest file from Azure Storage.
The manifest file contains list of all files in the group.
This URI expires in 24 hours. Required. """
    resource_endpoint: Optional[str] = rest_field(name="resourceEndpoint", readonly=True)
    """The endpoint uri of the owning resource. """

    @overload
    def __init__(
        self,
        *,
        upload_id: str,
        manifest_download_uri: str,
    ):
        ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]):
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """
        ...

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class Error(_model_base.Model):
    """The error object.

    All required parameters must be populated in order to send to Azure.

    :ivar code: One of a server-defined set of error codes. Required.
    :vartype code: str
    :ivar message: A human-readable representation of the error. Required.
    :vartype message: str
    :ivar target: The target of the error.
    :vartype target: str
    :ivar details: An array of details about specific errors that led to this reported error.
     Required.
    :vartype details: list[~adp.models.Error]
    :ivar innererror: An object containing more specific information than the current object about
     the error.
    :vartype innererror: ~adp.models.InnerError
    """

    code: str = rest_field()
    """One of a server-defined set of error codes. Required. """
    message: str = rest_field()
    """A human-readable representation of the error. Required. """
    target: Optional[str] = rest_field()
    """The target of the error. """
    details: List["_models.Error"] = rest_field()
    """An array of details about specific errors that led to this reported error. Required. """
    innererror: Optional["_models.InnerError"] = rest_field()
    """An object containing more specific information than the current object about the error. """

    @overload
    def __init__(
        self,
        *,
        code: str,
        message: str,
        details: List["_models.Error"],
        target: Optional[str] = None,
        innererror: Optional["_models.InnerError"] = None,
    ):
        ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]):
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """
        ...

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class ErrorResponse(_model_base.Model):
    """A response containing error details.

    All required parameters must be populated in order to send to Azure.

    :ivar error: The error object. Required.
    :vartype error: ~adp.models.Error
    """

    error: "_models.Error" = rest_field()
    """The error object. Required. """

    @overload
    def __init__(
        self,
        *,
        error: "_models.Error",
    ):
        ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]):
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """
        ...

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class InnerError(_model_base.Model):
    """An object containing more specific information about the error. As per Microsoft One API guidelines - https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md#7102-error-condition-responses.

    All required parameters must be populated in order to send to Azure.

    :ivar code: One of a server-defined set of error codes. Required.
    :vartype code: str
    :ivar innererror: Inner error.
    :vartype innererror: ~adp.models.InnerError
    """

    code: str = rest_field()
    """One of a server-defined set of error codes. Required. """
    innererror: Optional["_models.InnerError"] = rest_field()
    """Inner error. """

    @overload
    def __init__(
        self,
        *,
        code: str,
        innererror: Optional["_models.InnerError"] = None,
    ):
        ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]):
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """
        ...

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class LongRunningOperationWithResponseHeaders(_model_base.Model):
    """LongRunningOperationWithResponseHeaders.

    All required parameters must be populated in order to send to Azure.

    :ivar status: The operation status. Required. Known values are: "Created", "InProgress",
     "Succeeded", "Failed", and "Canceled".
    :vartype status: str or ~adp.models.LongRunningOperationStatus
    :ivar operation_type: The operation type.
    :vartype operation_type: str
    :ivar error: The operation error.
    :vartype error: ~adp.models.Error
    :ivar operation_id: The operation Id. Required.
    :vartype operation_id: str
    :ivar retry_after: The Retry-After header can indicate how long the client should wait before
     polling the operation status.
    :vartype retry_after: int
    :ivar location: Final location of the operation result.
    :vartype location: str
    """

    status: Union[str, "_models.LongRunningOperationStatus"] = rest_field()
    """The operation status. Required. Known values are: \"Created\", \"InProgress\", \"Succeeded\", \"Failed\", and \"Canceled\"."""
    operation_type: Optional[str] = rest_field(name="operationType")
    """The operation type. """
    error: Optional["_models.Error"] = rest_field()
    """The operation error. """
    operation_id: str = rest_field(name="operationId")
    """The operation Id. Required. """
    retry_after: Optional[int] = rest_field(name="retryAfter")
    """The Retry-After header can indicate how long the client should wait before polling the operation status. """
    location: Optional[str] = rest_field()
    """Final location of the operation result. """

    @overload
    def __init__(
        self,
        *,
        status: Union[str, "_models.LongRunningOperationStatus"],
        operation_id: str,
        operation_type: Optional[str] = None,
        error: Optional["_models.Error"] = None,
        retry_after: Optional[int] = None,
        location: Optional[str] = None,
    ):
        ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]):
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """
        ...

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class PagedDiscoverySpecialFile(_model_base.Model):
    """Paged collection of DiscoverySpecialFile items.

    All required parameters must be populated in order to send to Azure.

    :ivar value: The DiscoverySpecialFile items on this page. Required.
    :vartype value: list[~adp.models.DiscoverySpecialFile]
    :ivar next_link: The link to the next page of items.
    :vartype next_link: str
    """

    value: List["_models.DiscoverySpecialFile"] = rest_field()
    """The DiscoverySpecialFile items on this page. Required. """
    next_link: Optional[str] = rest_field(name="nextLink")
    """The link to the next page of items. """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class PagedDiscoveryUpload(_model_base.Model):
    """Paged collection of DiscoveryUpload items.

    All required parameters must be populated in order to send to Azure.

    :ivar value: The DiscoveryUpload items on this page. Required.
    :vartype value: list[~adp.models.DiscoveryUpload]
    :ivar next_link: The link to the next page of items.
    :vartype next_link: str
    """

    value: List["_models.DiscoveryUpload"] = rest_field()
    """The DiscoveryUpload items on this page. Required. """
    next_link: Optional[str] = rest_field(name="nextLink")
    """The link to the next page of items. """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class PagedUploadDataFile(_model_base.Model):
    """Paged collection of UploadDataFile items.

    All required parameters must be populated in order to send to Azure.

    :ivar value: The UploadDataFile items on this page. Required.
    :vartype value: list[~adp.models.UploadDataFile]
    :ivar next_link: The link to the next page of items.
    :vartype next_link: str
    """

    value: List["_models.UploadDataFile"] = rest_field()
    """The UploadDataFile items on this page. Required. """
    next_link: Optional[str] = rest_field(name="nextLink")
    """The link to the next page of items. """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class PagedUploadResultMeasurement(_model_base.Model):
    """Paged collection of UploadResultMeasurement items.

    All required parameters must be populated in order to send to Azure.

    :ivar value: The UploadResultMeasurement items on this page. Required.
    :vartype value: list[~adp.models.UploadResultMeasurement]
    :ivar next_link: The link to the next page of items.
    :vartype next_link: str
    """

    value: List["_models.UploadResultMeasurement"] = rest_field()
    """The UploadResultMeasurement items on this page. Required. """
    next_link: Optional[str] = rest_field(name="nextLink")
    """The link to the next page of items. """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class PagedUploadSpecialFile(_model_base.Model):
    """Paged collection of UploadSpecialFile items.

    All required parameters must be populated in order to send to Azure.

    :ivar value: The UploadSpecialFile items on this page. Required.
    :vartype value: list[~adp.models.UploadSpecialFile]
    :ivar next_link: The link to the next page of items.
    :vartype next_link: str
    """

    value: List["_models.UploadSpecialFile"] = rest_field()
    """The UploadSpecialFile items on this page. Required. """
    next_link: Optional[str] = rest_field(name="nextLink")
    """The link to the next page of items. """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class Upload(_model_base.Model):
    """An upload resource.

    Variables are only populated by the server, and will be ignored when sending a request.

    All required parameters must be populated in order to send to Azure.

    :ivar upload_id: The upload resource identifier. Required.
    :vartype upload_id: str
    :ivar external_package_id: ID of the external package (for example, the disk which contained
     data) which was used upon the creation of upload.
    :vartype external_package_id: str
    :ivar discovery_id: The discovery identifier.
    :vartype discovery_id: str
    :ivar manifest_upload_uri: SAS signed URI for uploading or reading the upload manifest file on
     Azure Storage.
     Note, if the upload status is 'Created' then the URI is signed with 'Write' permissions,
     otherwise with 'Read' permission.
     This URI expires in 24 hours.
    :vartype manifest_upload_uri: str
    :ivar status: The upload state. Known values are: "Created",
     "GeneratingSpecialFilesUploadInfo", "GeneratedSpecialFilesUploadInfo",
     "GeneratingDataFilesUploadInfo", "GeneratedDataFilesUploadInfo", "Completing", "Completed",
     "Aborting", "Aborted", and "Failed".
    :vartype status: str or ~adp.models.UploadStatus
    :ivar resource_endpoint: The endpoint uri of the owning resource.
    :vartype resource_endpoint: str
    """

    upload_id: str = rest_field(name="uploadId")
    """The upload resource identifier. Required. """
    external_package_id: Optional[str] = rest_field(name="externalPackageId", readonly=True)
    """ID of the external package (for example, the disk which contained data) which was used upon the creation of upload. """
    discovery_id: Optional[str] = rest_field(name="discoveryId", readonly=True)
    """The discovery identifier. """
    manifest_upload_uri: Optional[str] = rest_field(name="manifestUploadUri", readonly=True)
    """SAS signed URI for uploading or reading the upload manifest file on Azure Storage.
Note, if the upload status is 'Created' then the URI is signed with 'Write' permissions, otherwise with 'Read' permission.
This URI expires in 24 hours. """
    status: Optional[Union[str, "_models.UploadStatus"]] = rest_field(readonly=True)
    """The upload state. Known values are: \"Created\", \"GeneratingSpecialFilesUploadInfo\", \"GeneratedSpecialFilesUploadInfo\", \"GeneratingDataFilesUploadInfo\", \"GeneratedDataFilesUploadInfo\", \"Completing\", \"Completed\", \"Aborting\", \"Aborted\", and \"Failed\"."""
    resource_endpoint: Optional[str] = rest_field(name="resourceEndpoint", readonly=True)
    """The endpoint uri of the owning resource. """

    @overload
    def __init__(
        self,
        *,
        upload_id: str,
    ):
        ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]):
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """
        ...

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class UploadCreationParameters(_model_base.Model):
    """Upload resource creation parameters.

    Variables are only populated by the server, and will be ignored when sending a request.

    :ivar external_package_id: ID of the external package (for example, the disk which contained
     data) which was used upon the creation of upload.
    :vartype external_package_id: str
    :ivar discovery_id: The discovery identifier.
    :vartype discovery_id: str
    """

    external_package_id: Optional[str] = rest_field(name="externalPackageId", readonly=True)
    """ID of the external package (for example, the disk which contained data) which was used upon the creation of upload. """
    discovery_id: Optional[str] = rest_field(name="discoveryId", readonly=True)
    """The discovery identifier. """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class UploadDataFile(_model_base.Model):
    """Data file resource.

    All required parameters must be populated in order to send to Azure.

    :ivar client_file_name: File name specified by the client. Required.
    :vartype client_file_name: str
    :ivar file_upload_uri: SAS signed URI for uploading file to Azure Storage.
     This URI expires in 24 hours. Required.
    :vartype file_upload_uri: str
    """

    client_file_name: str = rest_field(name="clientFileName")
    """File name specified by the client. Required. """
    file_upload_uri: str = rest_field(name="fileUploadUri")
    """SAS signed URI for uploading file to Azure Storage.
This URI expires in 24 hours. Required. """

    @overload
    def __init__(
        self,
        *,
        client_file_name: str,
        file_upload_uri: str,
    ):
        ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]):
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """
        ...

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class UploadLroResponse(_model_base.Model):
    """The long running operation response.

    All required parameters must be populated in order to send to Azure.

    :ivar operation_id: The operation Id. Required.
    :vartype operation_id: str
    :ivar status: The operation status. Required. Known values are: "Created", "InProgress",
     "Succeeded", "Failed", and "Canceled".
    :vartype status: str or ~adp.models.LongRunningOperationStatus
    :ivar operation_type: The operation type. Known values are: "FinalizeFileList", "ShardFiles",
     "CompleteUpload", and "AbortUpload".
    :vartype operation_type: str or ~adp.models.UploadOperationType
    :ivar error: The operation error.
    :vartype error: ~adp.models.Error
    """

    operation_id: str = rest_field(name="operationId")
    """The operation Id. Required. """
    status: Union[str, "_models.LongRunningOperationStatus"] = rest_field()
    """The operation status. Required. Known values are: \"Created\", \"InProgress\", \"Succeeded\", \"Failed\", and \"Canceled\"."""
    operation_type: Optional[Union[str, "_models.UploadOperationType"]] = rest_field(name="operationType")
    """The operation type. Known values are: \"FinalizeFileList\", \"ShardFiles\", \"CompleteUpload\", and \"AbortUpload\"."""
    error: Optional["_models.Error"] = rest_field()
    """The operation error. """

    @overload
    def __init__(
        self,
        *,
        operation_id: str,
        status: Union[str, "_models.LongRunningOperationStatus"],
        operation_type: Optional[Union[str, "_models.UploadOperationType"]] = None,
        error: Optional["_models.Error"] = None,
    ):
        ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]):
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """
        ...

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class UploadResultMeasurement(_model_base.Model):
    """A measurement resource created as result of the upload.

    All required parameters must be populated in order to send to Azure.

    :ivar measurement_id: Measurement identifier. Required.
    :vartype measurement_id: str
    """

    measurement_id: str = rest_field(name="measurementId")
    """Measurement identifier. Required. """

    @overload
    def __init__(
        self,
        *,
        measurement_id: str,
    ):
        ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]):
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """
        ...

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class UploadSpecialFile(_model_base.Model):
    """Special file resource.

    All required parameters must be populated in order to send to Azure.

    :ivar client_file_name: File name specified by the client. Required.
    :vartype client_file_name: str
    :ivar file_upload_uri: SAS signed URI for uploading file to Azure Storage.
     This URI expires in 24 hours. Required.
    :vartype file_upload_uri: str
    """

    client_file_name: str = rest_field(name="clientFileName")
    """File name specified by the client. Required. """
    file_upload_uri: str = rest_field(name="fileUploadUri")
    """SAS signed URI for uploading file to Azure Storage.
This URI expires in 24 hours. Required. """

    @overload
    def __init__(
        self,
        *,
        client_file_name: str,
        file_upload_uri: str,
    ):
        ...

    @overload
    def __init__(self, mapping: Mapping[str, Any]):
        """
        :param mapping: raw JSON to initialize the model.
        :type mapping: Mapping[str, Any]
        """
        ...

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
